### ISSUE TITLE
Certification Checklist Grid

### ISSUE THREAD

**Issue by remomueller** [sleepepi/patstrial.org#33]
Allow users to be checked of as certified on a grid/spreadsheet of certifications. cc jbakker

From @mmorrical:

> Staff members will only need to complete the first two items, with all the rest being role-specific. It might make more sense to have a separate place to track all the individual items and a single blank or checked item in the staff directory when someone is completely done with their relevant items.

The full list of individual items to check off includes:
- [ ] Protocol Written Exam
- [ ] Conflict of Interest Form
- [ ] Slice Entry Practical Exam
- [ ] Anthropometry Practical Exam
- [ ] Blood Pressure Practical Exam
- [ ] Neurobehavioral Written Exam
- [ ] Neurobehavioral Practical Exam
- [ ] Actigraphy Written Exam
- [ ] Actigraphy Practical Exam
- [ ] Actigraphy Recording _#_1
- [ ] Actigraphy Recording _#_2
- [ ] PSG Written Exam
- [ ] PSG Practical Exam
- [ ] PSG Recording _#_1
- [ ] PSG Recording _#_2
- [ ] Surgical Attestation Form

**Comment by remomueller** [comment]
Closing issue, certification is done outside of the portal
